### ISSUE TITLE
アプリ起動時に NullPointerException で終了する

### ISSUE THREAD

**Issue by yuukis** [yuukis/businessmap#12]
**v1.0.0115** で発生

> java.lang.NullPointerException
> at android.database.sqlite.SQLiteDatabase.closeDatabase(SQLiteDatabase.java:1288)
> at android.database.sqlite.SQLiteDatabase.close(SQLiteDatabase.java:1237)
> at com.github.yuukis.businessmap.data.GeocodingCacheDatabase.close(GeocodingCacheDatabase.java:90)
> at com.github.yuukis.businessmap.app.MainActivity.loadAllContacts(MainActivity.java:352)
> at com.github.yuukis.businessmap.app.MainActivity.access$0(MainActivity.java:197)
> at com.github.yuukis.businessmap.app.MainActivity$GeocodingThread.run(MainActivity.java:369)

**Comment by yuukis** [comment]
改善されたか、実機で動作確認中

**Comment by yuukis** [comment]
**v1.0.0116** でも発生

> java.lang.NullPointerException
> at android.database.sqlite.SQLiteDatabase.closeDatabase(SQLiteDatabase.java:1288)
> at android.database.sqlite.SQLiteDatabase.close(SQLiteDatabase.java:1237)
> at com.github.yuukis.businessmap.data.GeocodingCacheDatabase.close(GeocodingCacheDatabase.java:91)
> at com.github.yuukis.businessmap.app.MainActivity.loadAllContacts(MainActivity.java:352)
> at com.github.yuukis.businessmap.app.MainActivity.access$0(MainActivity.java:197)
> at com.github.yuukis.businessmap.app.MainActivity$GeocodingThread.run(MainActivity.java:369)

**Comment by yuukis** [comment]
**v1.0.0122** でも発生

> java.lang.NullPointerException
> at android.database.sqlite.SQLiteDatabase.closeDatabase(SQLiteDatabase.java:1288)
> at android.database.sqlite.SQLiteDatabase.close(SQLiteDatabase.java:1237)
> at com.github.yuukis.businessmap.data.GeocodingCacheDatabase.close(GeocodingCacheDatabase.java:91)
> at com.github.yuukis.businessmap.app.MainActivity.loadAllContacts(MainActivity.java:382)
> at com.github.yuukis.businessmap.app.MainActivity.access$0(MainActivity.java:210)
> at com.github.yuukis.businessmap.app.MainActivity$GeocodingThread.run(MainActivity.java:399)
