### ISSUE TITLE
ContactsMapFragment#onActivityCreated で NPE

### ISSUE THREAD

**Issue by yuukis** [yuukis/businessmap#17]
**v1.1.0130** で発生

> java.lang.RuntimeException: Unable to start activity ComponentInfo{com.github.yuukis.businessmap/com.github.yuukis.businessmap.app.MainActivity}: java.lang.NullPointerException
> at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1973)
> at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1998)
> at android.app.ActivityThread.access$600(ActivityThread.java:129)
> at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1164)
> at android.os.Handler.dispatchMessage(Handler.java:99)
> at android.os.Looper.loop(Looper.java:137)
> at android.app.ActivityThread.main(ActivityThread.java:4479)
> at java.lang.reflect.Method.invokeNative(Native Method)
> at java.lang.reflect.Method.invoke(Method.java:511)
> at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
> at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
> at dalvik.system.NativeStart.main(Native Method)
> Caused by: java.lang.NullPointerException
> at com.github.yuukis.businessmap.app.ContactsMapFragment.onActivityCreated(ContactsMapFragment.java:62)
> at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:847)
> at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1032)
> at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1014)
> at android.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:1766)
> at android.app.Activity.performCreate(Activity.java:4468)
> at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1049)
> at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1937)
> ... 11 more

**Comment by yuukis** [comment]
http://stackoverflow.com/questions/19219255/supportmapfragment-getmap-returns-null
