### ISSUE TITLE
android.database.CursorWindowAllocationException (GeocodingCacheDatabase#get)

### ISSUE THREAD

**Issue by yuukis** [yuukis/businessmap#18]
**v1.1.0130** で発生

> android.database.CursorWindowAllocationException: Cursor window allocation of 2048 kb failed. # Open Cursors=498 (# cursors opened by this proc=498)
> at android.database.CursorWindow.<init>(CursorWindow.java:104)
> at android.database.AbstractWindowedCursor.clearOrCreateWindow(AbstractWindowedCursor.java:198)
> at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:139)
> at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:133)
> at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:197)
> at android.database.AbstractCursor.moveToNext(AbstractCursor.java:245)
> at com.github.yuukis.businessmap.data.GeocodingCacheDatabase.get(GeocodingCacheDatabase.java:59)
> at com.github.yuukis.businessmap.app.MainActivity.loadAllContacts(MainActivity.java:330)
> at com.github.yuukis.businessmap.app.MainActivity.access$0(MainActivity.java:220)
> at com.github.yuukis.businessmap.app.MainActivity$GeocodingThread.run(MainActivity.java:409)

**Comment by yuukis** [comment]
http://stackoverflow.com/questions/12577400/out-of-memory-when-allocating-cursors

**Comment by yuukis** [comment]
http://qarc.info/qa/show-10827-529.html
