### ISSUE TITLE
java.lang.StackOverflowError at ArrayList#toArray

### ISSUE THREAD

**Issue by yuukis** [yuukis/businessmap#19]
**v1.1.0135** で発生

> java.lang.StackOverflowError
> at java.util.ArrayList.toArray(ArrayList.java:493)
> at maps.as.ay.b(Unknown Source)
> at maps.as.ay.a(Unknown Source)
> at maps.h.q.e(Unknown Source)
> at maps.h.q.f(Unknown Source)
> at maps.h.q.m(Unknown Source)
> at maps.h.q.d(Unknown Source)
> at maps.h.q.c(Unknown Source)
> at maps.h.q.a(Unknown Source)
> at maps.h.q.b(Unknown Source)
> at maps.h.q.f(Unknown Source)
> at maps.h.q.m(Unknown Source)
> at maps.h.q.d(Unknown Source)
> at maps.h.q.c(Unknown Source)
> at maps.h.q.a(Unknown Source)
> at maps.h.q.b(Unknown Source)
>   ...
> at maps.h.q.f(Unknown Source)
> at maps.h.q.m(Unknown Source)
> at maps.h.q.l(Unknown Source)
> at maps.h.q.a(Unknown Source)
> at maps.ao.ad.b(Unknown Source)
> at maps.v.f.a(Unknown Source)
> at maps.v.f.b(Unknown Source)
> at maps.p.l.l(Unknown Source)
> at maps.p.l.run(Unknown Source)

**Comment by yuukis** [comment]
http://d.hatena.ne.jp/takeR/20131025/1382693789

**Comment by yuukis** [comment]
http://stackoverflow.com/questions/15453542/fatal-exception-glthread-stackoverflowerror-with-google-maps-v2
