### ISSUE TITLE
java.lang.NullPointerException at GeocoderUtils#getFromLocationNameToGoogleMaps

### ISSUE THREAD

**Issue by yuukis** [yuukis/businessmap#21]
**v1.1.0135** で発生

> java.lang.NullPointerException
> at com.github.yuukis.businessmap.utils.GeocoderUtils.getFromLocationNameToGoogleMaps(GeocoderUtils.java:76)
> at com.github.yuukis.businessmap.utils.GeocoderUtils.getFromLocationName(GeocoderUtils.java:41)
> at com.github.yuukis.businessmap.app.MainActivity$GeocodingThread.geocoding(MainActivity.java:453)
> at com.github.yuukis.businessmap.app.MainActivity$GeocodingThread.run(MainActivity.java:411)

**Comment by yuukis** [comment]
https://groups.google.com/forum/#!topic/android-group-japan/hSbmsmVPOpo
⇒1,2件程度であれば通るので、上記は該当しない？

**Comment by yuukis** [comment]
https://developers.google.com/maps/documentation/geocoding/?hl=ja

> Google Geocoding API 使用時のクエリ制限として、1 日あたりの位置情報リクエストが 2,500 回に制限されています（Google Maps API for Business をご利用の場合は、1 日あたり 100,000 件までリクエストを実行できます）。

**Comment by yuukis** [comment]
``` java
        JSONObject jsonObject = null;
        try {
            jsonObject = new JSONObject(stringBuilder.toString());
        } catch (JSONException e) {
            e.printStackTrace();
        }
```

jsonObject が null になるもよう

**Comment by yuukis** [comment]
- Google Geocoding API の結果が JSON で返ってこなかった場合を考慮すべき
- Geocoding 処理回数の上限を設けた方が良い？
