### ISSUE TITLE
java.lang.IllegalArgumentException at CursorJoinerWithIntKey#buildColumnIndiciesArray

### ISSUE THREAD

**Issue by yuukis** [yuukis/businessmap#23]
**v1.1.0135** で発生

> java.lang.IllegalArgumentException: column 'raw_contact_id' does not exist
> at android.database.AbstractCursor.getColumnIndexOrThrow(AbstractCursor.java:303)
> at android.database.CursorWrapper.getColumnIndexOrThrow(CursorWrapper.java:78)
> at com.github.yuukis.businessmap.utils.CursorJoinerWithIntKey.buildColumnIndiciesArray(CursorJoinerWithIntKey.java:63)
> at com.github.yuukis.businessmap.utils.CursorJoinerWithIntKey.<init>(CursorJoinerWithIntKey.java:50)
> at com.github.yuukis.businessmap.app.MainActivity.loadAllContacts(MainActivity.java:271)
> at com.github.yuukis.businessmap.app.MainActivity.access$0(MainActivity.java:220)
> at com.github.yuukis.businessmap.app.MainActivity$GeocodingThread.run(MainActivity.java:409)

**Comment by yuukis** [comment]
**v1.4.0226** で発生

> java.lang.RuntimeException: An error occured while executing doInBackground()
> at android.os.AsyncTask$3.done(AsyncTask.java:299)
> at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:352)
> at java.util.concurrent.FutureTask.setException(FutureTask.java:219)
> at java.util.concurrent.FutureTask.run(FutureTask.java:239)
> at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
> at java.lang.Thread.run(Thread.java:856)
> Caused by: java.lang.IllegalArgumentException: column 'raw_contact_id' does not exist / exist columns:
> at com.github.yuukis.businessmap.util.CursorJoinerWithIntKey.buildColumnIndiciesArray(CursorJoinerWithIntKey.java:71)
> at com.github.yuukis.businessmap.util.CursorJoinerWithIntKey.<init>(CursorJoinerWithIntKey.java:51)
> at com.github.yuukis.businessmap.app.ContactsTaskFragment$ContactsAsyncTask.loadAllContacts(ContactsTaskFragment.java:337)
> at com.github.yuukis.businessmap.app.ContactsTaskFragment$ContactsAsyncTask.doInBackground(ContactsTaskFragment.java:235)
> at com.github.yuukis.businessmap.app.ContactsTaskFragment$ContactsAsyncTask.doInBackground(ContactsTaskFragment.java:1)
> at android.os.AsyncTask$2.call(AsyncTask.java:287)
> at java.util.concurrent.FutureTask.run(FutureTask.java:234)
> ... 4 more

**Comment by yuukis** [comment]
SHARP SHL22, SHL24 で発生している

**Comment by yuukis** [comment]
手元の端末で再現できず

**Comment by yuukis** [comment]
現行コードとの関係を再確認しました。

このIssueで例外が発生した処理経路は現在も残っています。`MainActivityViewModel.loadAllContacts()` はContactsProviderへ `raw_contact_id` を含むprojectionを指定し、`CursorJoinerWithIntKey` は返却されたCursorから同列を `getColumnIndexOrThrow()` で取得しています。そのため、Providerがprojectionどおりの列を返さない場合は、現在も同種の `IllegalArgumentException` が発生し得ます。

一方、現在の実装では連絡先読み込み中の想定外の例外を捕捉し、エラー表示へ変換するため、当時のようにアプリ全体がクラッシュする可能性は下がっています。また、報告端末のSHARP SHL22/SHL24は現在のminSdk 26の対象外です。

したがって、報告端末固有の再現条件は現行アプリには該当しませんが、コード上の根本的な列依存は残っているため、Issue自体は完全に無関係とは判断できません。現行AndroidのContactsProviderで同様のCursorが返る可能性を考慮し、互換性問題として継続調査するのがよさそうです。
