### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by yuukis** [yuukis/businessmap#34]
**v1.4.0224** で発生

> java.lang.NullPointerException
> at android.widget.TextView.makeNewLayout(TextView.java:6241)
> at android.widget.TextView.onMeasure(TextView.java:6532)
> at android.view.View.measure(View.java:16609)
> at android.widget.Spinner.setUpChild(Spinner.java:632)
> at android.widget.Spinner.makeView(Spinner.java:595)
> at android.widget.Spinner.getBaseline(Spinner.java:431)
> at android.widget.LinearLayout.measureHorizontal(LinearLayout.java:1089)
> at android.widget.LinearLayout.onMeasure(LinearLayout.java:590)
> at android.view.View.measure(View.java:16609)
> at com.android.internal.widget.ActionBarView.onMeasure(ActionBarView.java:1003)
> at android.view.View.measure(View.java:16609)
> at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
> at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
> at com.android.internal.widget.ActionBarContainer.onMeasure(ActionBarContainer.java:271)
> at android.view.View.measure(View.java:16609)
> at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
> at com.android.internal.widget.ActionBarOverlayLayout.onMeasure(ActionBarOverlayLayout.java:254)
> at android.view.View.measure(View.java:16609)
> at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
> at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
> at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2305)
> at android.view.View.measure(View.java:16609)
> at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:1975)
> at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1128)
> at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1310)
> at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1015)
> at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5762)
> at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
> at android.view.Choreographer.doCallbacks(Choreographer.java:574)
> at android.view.Choreographer.doFrame(Choreographer.java:544)
> at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
> at android.os.Handler.handleCallback(Handler.java:733)
> at android.os.Handler.dispatchMessage(Handler.java:95)
> at android.os.Looper.loop(Looper.java:136)
> at android.app.ActivityThread.main(ActivityThread.java:5191)
> at java.lang.reflect.Method.invokeNative(Native Method)
> at java.lang.reflect.Method.invoke(Method.java:515)
> at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:805)
> at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:621)
> at dalvik.system.NativeStart.main(Native Method)

**Comment by yuukis** [comment]
http://stackoverflow.com/questions/20176877/weird-nullpointerexception-in-spinner
