### ISSUE TITLE
java.lang.NoSuchMethodError at com.google.maps.api.android

### ISSUE THREAD

**Issue by yuukis** [yuukis/businessmap#35]
**v1.4.0226** で発生
Android 2.3.3 - 2.3.7

> java.lang.NoSuchMethodError: android.view.ViewParent.requestSendAccessibilityEvent
> at com.google.maps.api.android.lib6.c.bc.a(Unknown Source)
> at com.google.maps.api.android.lib6.c.ai.a(Unknown Source)
> at com.google.maps.api.android.lib6.c.ax.f(Unknown Source)
> at com.google.maps.api.android.lib6.c.do.handleMessage(Unknown Source)
> at android.os.Handler.dispatchMessage(Handler.java:99)
> at android.os.Looper.loop(Looper.java:130)
> at android.app.ActivityThread.main(ActivityThread.java:3691)
> at java.lang.reflect.Method.invokeNative(Native Method)
> at java.lang.reflect.Method.invoke(Method.java:507)
> at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:907)
> at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:665)
> at dalvik.system.NativeStart.main(Native Method)

**Comment by yuukis** [comment]
NoSuchMethodError in google maps api android
http://stackoverflow.com/questions/26335434/nosuchmethoderror-in-google-maps-api-android

**Comment by yuukis** [comment]
現行コードとの関係を再確認しました。

このIssueはAndroid 2.3.3〜2.3.7上のGoogle Maps API内部で発生した `ViewParent.requestSendAccessibilityEvent` の `NoSuchMethodError` ですが、現在のアプリはminSdk 26（Android 8.0）で、Google Maps SDKも `com.google.android.gms:play-services-maps:20.0.0` を使用しています。

問題が発生したOSバージョンには現在のアプリをインストールできず、当時のMaps API実装も使用していないため、現行コードでは再発対象外です。このIssueはobsoleteとしてクローズして問題ないと判断します。
